In [36]:
import numpy as np

In [37]:
a = np.array([1, 2, 3, 4], dtype = "uint8")
a

array([1, 2, 3, 4], dtype=uint8)

In [38]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b.shape

(3, 3)

In [39]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
c = np.zeros((3, 4), dtype="uint32")
c[0, 3] = 10
c[1, 1] = 1
c += 100
c

array([[100, 100, 100, 110],
       [100, 101, 100, 100],
       [100, 100, 100, 100]], dtype=uint32)

In [41]:
b = 11 * np.ones((3, 1))
b

array([[11.],
       [11.],
       [11.]])

In [42]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
a[::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
a[::2]

array([ 0,  2,  4,  6,  8, 10])

In [44]:
a[::3]

array([0, 3, 6, 9])

In [45]:
a[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [47]:
a[::-2]

array([11,  9,  7,  5,  3,  1])

In [ ]:
a = a.reshape((3, 4))
a

In [ ]:
a[1]

In [ ]:
a[1,:]

In [ ]:
a[1] = [44, 55, 66, 77]
a

In [ ]:
a[:2]

In [ ]:
a[:2:]

In [ ]:
a[:2, :3]

In [ ]:
b = range(0, 10)
b

In [48]:
c = np.arange(24).reshape((4, 3, 2))
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [49]:
c[1,:,:] = [[60, 70], [80, 90], [100, 110]]
c

array([[[  0,   1],
        [  2,   3],
        [  4,   5]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]],

       [[ 12,  13],
        [ 14,  15],
        [ 16,  17]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]]])

In [50]:
c[1,:,:] = c[1,:,:] / 10
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [51]:
c[2,...] = [[120, 130], [140, 150], [160, 170]]
c

array([[[  0,   1],
        [  2,   3],
        [  4,   5]],

       [[  6,   7],
        [  8,   9],
        [ 10,  11]],

       [[120, 130],
        [140, 150],
        [160, 170]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]]])

In [53]:
c[2,...] = c[2,...] / 10
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [55]:
r = np.random.randint(0, 10, (3,4))
r

array([[3, 5, 6, 8],
       [3, 5, 9, 5],
       [3, 0, 7, 5]])

In [56]:
np.save("random.npy", r)
r2 = np.load("random.npy")
r2

array([[3, 5, 6, 8],
       [3, 5, 9, 5],
       [3, 0, 7, 5]])