In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4], dtype = "uint8")
a

array([1, 2, 3, 4], dtype=uint8)

In [5]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b.shape

(3, 3)

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
c = np.zeros((3, 4), dtype="uint32")
c[0, 3] = 10
c[1, 1] = 1
c += 100
c

array([[100, 100, 100, 110],
       [100, 101, 100, 100],
       [100, 100, 100, 100]], dtype=uint32)

In [8]:
b = 11 * np.ones((3, 1))
b

array([[11.],
       [11.],
       [11.]])

In [9]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
a[::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
a[::2]

array([ 0,  2,  4,  6,  8, 10])

In [12]:
a[::3]

array([0, 3, 6, 9])

In [13]:
a[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [14]:
a[::-2]

array([11,  9,  7,  5,  3,  1])

In [15]:
a = a.reshape((3, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
a[1]

array([4, 5, 6, 7])

In [17]:
a[1,:]

array([4, 5, 6, 7])

In [18]:
a[1] = [44, 55, 66, 77]
a

array([[ 0,  1,  2,  3],
       [44, 55, 66, 77],
       [ 8,  9, 10, 11]])

In [19]:
a[:2]

array([[ 0,  1,  2,  3],
       [44, 55, 66, 77]])

In [20]:
a[:2:]

array([[ 0,  1,  2,  3],
       [44, 55, 66, 77]])

In [21]:
a[:2, :3]

array([[ 0,  1,  2],
       [44, 55, 66]])

In [22]:
b = range(0, 10)
b

range(0, 10)

In [23]:
c = np.arange(24).reshape((4, 3, 2))
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [24]:
c[1,:,:] = [[60, 70], [80, 90], [100, 110]]
c

array([[[  0,   1],
        [  2,   3],
        [  4,   5]],

       [[ 60,  70],
        [ 80,  90],
        [100, 110]],

       [[ 12,  13],
        [ 14,  15],
        [ 16,  17]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]]])

In [25]:
c[1,:,:] = c[1,:,:] / 10
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [26]:
c[2,...] = [[120, 130], [140, 150], [160, 170]]
c

array([[[  0,   1],
        [  2,   3],
        [  4,   5]],

       [[  6,   7],
        [  8,   9],
        [ 10,  11]],

       [[120, 130],
        [140, 150],
        [160, 170]],

       [[ 18,  19],
        [ 20,  21],
        [ 22,  23]]])

In [27]:
c[2,...] = c[2,...] / 10
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [28]:
r = np.random.randint(0, 10, (3,4))
r

array([[6, 3, 6, 5],
       [1, 8, 3, 5],
       [5, 3, 6, 4]])

In [29]:
np.save("random.npy", r)
r2 = np.load("random.npy")
r2

array([[6, 3, 6, 5],
       [1, 8, 3, 5],
       [5, 3, 6, 4]])